// <auto-generated />
namespace LawCalculator_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProjectToLawyersProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProjectToLawyersProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202104271926153_Add Project To LawyersProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
